apiVersion: nais.io/v1
kind: Alert
metadata:
  name: q1-alerts-for-tpordninger
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  receivers:
    slack:
      channel: '#testmiljø-tjenestepensjon'
  alerts:
    - alert: App nede
      expr: up{app=~"samordning-inn|tpregisteret",job="black box scraping of ingresses"} == 0
      for: 5m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: Sjekk logger i Q1 her - https://logs.adeo.no/goto/df6e36529831a8f79533b296c2741efc
      severity: danger
